name: rocksdb-haskell-jprupp
version: 2.1.6
synopsis: Haskell bindings for RocksDB
description: See README at <https://github.com/jprupp/rocksdb-haskell#readme>
maintainer: Jean-Pierre Rupp <jprupp@protonmail.ch>
github: jprupp/rocksdb-haskell
category: Database, FFI
license: BSD3
license-file: LICENSE
extra-source-files:
  - README.md
  - CHANGELOG.md
  - AUTHORS

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - data-default
  - directory
  - resourcet
  - unliftio

library:
  source-dirs: src
  exposed-modules:
    Database.RocksDB
  extra-libraries: rocksdb

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rocksdb-haskell-jprupp
      - hspec
      - QuickCheck
